[project]
name = "gmail-imap-mcp"
version = "0.1.0"
description = "A Gmail MCP server using IMAP"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "mcp>=1.3.0",
    "google-auth>=2.28.0",
    "google-auth-oauthlib>=1.2.0",
    "google-api-python-client>=2.120.0",
    "imaplib2>=3.6",
    "pydantic>=2.6.0",
]
[[project.authors]]
name = "Tony Kipkemboi"
email = "iamtonykipkemboi@gmail.com"

[build-system]
requires = [ "hatchling",]
build-backend = "hatchling.build"

[project.scripts]
gmail-imap-mcp = "gmail_imap_mcp:main"
